# Generated by Django 2.1.7 on 2019-03-19 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrelease',
            name='task_deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 13, 26, 7, 403755), verbose_name='任务时限'),
        ),
    ]
